name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
categories:
  - title: 'Features 🚀'
    labels:
      - 'enhancement'

  - title: 'Bug Fixes 🐛'
    labels:
      - 'bug'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
  ## Thank you so much for helping out !
  $CONTRIBUTORS